### PR TITLE
Use config Newline Setting In System Attribute Evaluation (#154)

### LINKED ISSUE #154: 9.0.4 adding DOS line endings to a few lines
I package fldigi for Fedora linux and when asciidoc was updated to 9.0.4 the build started failing with strange errors. Asciidoc is used to generate an html file from a text file, which is then subsequently processed via sed to produce a c++ file suitable for inclusion.

For some reason 3 lines are getting ^M dos line endings of about a 1000 line file.

```
--- fedora-33-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.html     2020-12-03 08:19:54.596151576 -0600
+++ fedora-rawhide-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.html        2020-12-03 07:40:44.117096417 -0600
@@ -4,7 +4,7 @@
 <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
 <head>
 <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
-<meta name="generator" content="AsciiDoc 9.0.2" />
+<meta name="generator" content="AsciiDoc 9.0.4" />
 <title>Beginners' Guide to Fldigi</title>
 <style type="text/css">
 /* Shared CSS for AsciiDoc xhtml11 and html5 backends */
@@ -735,9 +735,9 @@
 <body class="article">
 <div id="header">
 <h1>Beginners' Guide to Fldigi</h1>
-<div id="toc">
-  <div id="toctitle">Table of Contents</div>
-  <noscript><p><b>JavaScript must be enabled in your browser to display the table of contents.</b></p></noscript>
+<div id="toc">
+  <div id="toctitle">Table of Contents</div>
+  <noscript><p><b>JavaScript must be enabled in your browser to display the table of contents.</b></p></noscript>
 </div>
 </div>
 <div id="content">
```

It doesn't show in the diff unless using a paginator but obviously diff is seeing the lines as different. Fedora 33 has 9.0.2 while Fedora 34 (Rawhide) has 9.0.4.

```
# file fedora-33-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.txt
fedora-33-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.txt: UTF-8 Unicode text
# file fedora-33-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.html
fedora-33-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.html: XML 1.0 document, UTF-8 Unicode text
# file fedora-rawhide-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.txt
fedora-rawhide-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.txt: UTF-8 Unicode text
# file fedora-rawhide-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.html
fedora-rawhide-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.html: XML 1.0 document, UTF-8 Unicode text, with CRLF, LF line terminators
```

For some reason the CRLF terminators are working their way in but they are not present in the guide.txt input file.

### PR DESCRIPTION
**Pull request by hoadlck**
Problems seen with inconsistent newlines in the Table Of Contents HTML pulled in from the configuration file.  While the rest of the contents in the resulting HTML file honored the newline style configured by the user, this specific snippet of HTML always used "\r\n".

This root of this problem existed for some time, but in earlier versions, the newline style was always "\n".  The symptoms changed as a side effect of the issue "Extra line padding in source and literal blocks" (#139).  In this issue, the newline style changed to "\r\n", and was noticed by users.

Change the System Attribute Evaluation function to use the newline setting from the global "config" instead of using the default newline.

Closes #154

### CODE REVIEW

**Comment by MasterOdin** [comment]
Can we also change these two lines to use config.newline while we're at it:
https://github.com/asciidoc/asciidoc-py3/blob/89ac0f48affb054226467b58f5af524ae0760d62/asciidoc.py#L3637-L3638
https://github.com/asciidoc/asciidoc-py3/blob/89ac0f48affb054226467b58f5af524ae0760d62/asciidoc.py#L5656

Could you add a test case of a file that specifies newline as a configuration option in the test suite? (Feel free to say no, and I can handle this).

I'll take a look at the test suite today to get that working.

**Comment by hoadlck** [comment]
This is for #154.

I noticed two other areas where DEFAULT_NEWLINE was used, and I did not change them.  Both of these were in the context of reading csv files.  If they are an issue (which I would need to research more to see if they are), then I don't know if it would be preferred to put it in another PR, or extend this one.

**Comment by MasterOdin** [comment]
Fair enough, I did not look very deeply into it, I'll open a separate issue to track that, and we can leave this PR to just focus on the use-case of #154.

**Comment by hoadlck** [comment]
Looks like the tests are failing because of some commands that GitHub deprecated.  They no longer allow the `app-path` commands.  The error referenced [this documenation](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/).

Here is the error:
```
Error: Unable to process command '::add-path::/home/runner/venv-3.10/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

**Comment by MasterOdin** [comment]
Yup, easy enough fix in #156 and now on master. Would you mind merging master into your branch?

**Comment by MasterOdin** [comment]
Thanks. Last bit was just confirming if you think you could add a test case for this?

**Comment by hoadlck** [comment]
Sure, I can add a test case.  It will be tonight (or maybe tomorrow) before I will have time to look at it though.  But, I have wanted to understand how the tests worked for some time.

If you want to get the release out sooner than that, it won't hurt my feelings if you add the test case. :-)

**Comment by MasterOdin** [comment]
:+1:

I'm fine waiting a few days for you to write the test if it means having more collaborators know the repository more fully.

**Comment by hoadlck** [comment]
I pushed an update with the tests for newlines.  I added a new test input file that has 3 sections:  each section is in a different newline style (DOS/UNIX/MAC).  I enable the TOC so that the original issue would be visible if it ever came back.

Let me know if there are any changes you think would be a good idea.

**Comment by hoadlck** [comment]
I looked into the uses of `DEFAULT_NEWLINE` where it is used in `csv.reader()`.  The usage is in the context of reading a .csv file to determine the contents of a table.  Since the individual cells are extracted by the csv reader, the new lines do not really matter.

It looks like the caller of the `parse_csv()` method has already broken the csv lines into a list, so the `DEFAULT_NEWLINE.join(text)` is just a way to put the text into a format that the normal csv reader code can parse it.  I tried having the csv with different line endings, but it did not make any difference in the output.

I even tried making a cell have multiple lines in the csv.  The output HTML did honor the specified newline (not the newline that was embedded in the csv).  Of course, the rendered text for the multi-line cell all appeared to be on one line.  Which seems like the correct functionality.

I don't see any tests that use a csv file as input for a table.  Do you want me to include one in this PR, or reserve that for another?

**Comment by hoadlck** [comment]
> I don't see any tests that use a csv file as input for a table. Do you want me to include one in this PR, or reserve that for another?

Never mind...I see that the tables test is using a csv from the website area.  So, I think this PR is ready as-is.

**Comment by MasterOdin** [comment]
Thanks for this! The tests look good and the generated html files have the expected line endings. Did a manual test on #154 with provided `guide.txt` and `asciidoc.conf` with just the specified attributes and that looks good as well.

**Pull request merged**
