### PR TITLE
INSTALL.txt: Minor typo fixes and style tweaks

### PR DESCRIPTION
**Pull request by apjanke**
This has some minor fixes for typo and grammar errors in INSTALL.txt.
Also includes some formatting and wording adjustments to make it internally consistent, and to match GitHub's styling of their name.

### CODE REVIEW

**Comment by elextr** [comment]
Umm, IAW #31 are any of the listed distributions correct for Asciidoc-py3?  

Maybe better to take them all out unless they are known to be right, rather than twiddle with incorrect entries :)

**Comment by apjanke** [comment]
AFAIK they are all pointing at the old AsciiDoc.

I will check the links for them and remove the stale ones in a separate PR.

**Comment by apjanke** [comment]
Right you are. https://github.com/asciidoc/asciidoc-py3/pull/41

**Comment by apjanke** [comment]
Speaking of package managers, would you be interested in a Mac Homebrew formula for asciidoc-py3 so it could be easily installed on macOS? Might make it easier to get people to test it.

**Comment by elextr** [comment]
> would you be interested in a Mac Homebrew formula for asciidoc-py3 so it could be easily installed on macOS?

Being Apple illiterate and intending to stay that way, if its only a single file that specifies installation then it probably isn't a problem.

**Comment by elextr** [comment]
> Being Apple illiterate and intending to stay that way

Dammit I learned something https://formulae.brew.sh/formula/asciidoc :grin:

If the download counts are right thats a bit of a worry for a version thats coming to EOL, so if a Python 3 version is listed that would be good.  

And then is it possible to have the Python 2 entry advise using the -py3 version after its made available?

**Comment by apjanke** [comment]
>  if its only a single file that specifies installation then it probably isn't a problem.

It would be a single file (and maybe a README to go with it), but it needs to be maintained in a [separate repo that functions as a Homebrew "tap"](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md). This is their mechanism for supporting third-party formula definitions.

> And then is it possible to have the Python 2 entry advise using the -py3 version after its made available?

The asciidoc-py3 project looks a little young to be listed in core Homebrew yet.  But you could set up this "custom" asciidoc-py3 formula for use during the port/migration, and if the migration to py3 is successful, the main Homebrew asciidoc formula could be changed to use the new py3 version, which would migrate all the existing users over when they did a `brew upgrade`. Then the custom formula could then go away, unless you wanted to keep it around for testing pre-release versions.

**Comment by apjanke** [comment]
Opened up a new issue for discussion: https://github.com/asciidoc/asciidoc-py3/issues/43

**Pull request merged**
