### PR TITLE
allow floating dblatex figures, examples, equations and tables with floatstyle attribute

### PR DESCRIPTION
**Pull request by psaris**
dblatex permits setting the floating attribute for figures, examples, equations and tables by specifying the floatstyle attribute.  example xsl shown below:

```xml
<xsl:template match="figure">
  <xsl:text>\begin{figure}</xsl:text>
  <!-- figure placement preference -->
  <xsl:choose>
    <xsl:when test="@floatstyle != ''">
      <xsl:value-of select="@floatstyle"/>
    </xsl:when>
    <xsl:when test="not(@float) or (@float and @float='0')">
      <xsl:text>[H]</xsl:text>
    </xsl:when>
    <xsl:otherwise>
      <xsl:value-of select="$figure.default.position"/>
    </xsl:otherwise>
  </xsl:choose>
  <xsl:text>&#10;</xsl:text>
```

```xml
  <xsl:value-of select="concat('\begin{', $table.env, '}')"/>
  <!-- table placement preference -->
  <xsl:choose>
    <xsl:when test="@floatstyle != ''">
      <xsl:value-of select="@floatstyle"/>
    </xsl:when>
    <xsl:otherwise>
      <xsl:value-of select="$table.default.position"/>
    </xsl:otherwise>
  </xsl:choose>
```

```xml
    <xsl:text>&#10;\begin{dbequation}</xsl:text>
    <!-- float placement preference -->
    <xsl:choose>
      <xsl:when test="@floatstyle != ''">
        <xsl:value-of select="@floatstyle"/>
      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="$equation.default.position"/>
      </xsl:otherwise>
    </xsl:choose>
```

```xml
<xsl:template match="example" mode="float">
  <xsl:text>&#10;\begin{example}</xsl:text>
  <!-- float placement preference -->
  <xsl:choose>
    <xsl:when test="@floatstyle != ''">
      <xsl:value-of select="@floatstyle"/>
    </xsl:when>
    <xsl:otherwise>
      <xsl:value-of select="$example.default.position"/>
    </xsl:otherwise>
  </xsl:choose>
```

### CODE REVIEW

**Comment by psaris** [comment]
is there anything else needed to merge this PR?

**Comment by MasterOdin** [comment]
Sorry for the delay on reviewing this. It looks alright, but I've not got much experience with docbook.

Would you be able to write some example asciidoc files that demonstrate usage of the attribute as well for the different usages that you've included?

**Comment by psaris** [comment]
please give me a bit more time, just finishing up an actual book using these features. will add examples in a few days.

**Comment by psaris** [comment]
added new formal latexmath and example sections to tests/data/testcases.txt so that all four float types can be demonstrated in the docbook and docbook5 backends.

**Comment by MasterOdin** [comment]
Thanks for this, it will be included in 9.0 final.

**Pull request merged**
